server:
  port: 8090
## Mybatis plus配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lmj.estate.entity
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
##Spring 配置
spring:
  # DataSourceProperties
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/estate?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  ##上传文件的最大限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
##日志配置
logging:
  level:
    com.lmj.estate: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/"
